steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/mi-proyecto/mi-imagen'
      - '.'

options:
  logging: CLOUD_STORAGE

build:
  service_account: 'mi-cuenta-de-servicio@mi-proyecto.iam.gserviceaccount.com'
  logs_bucket: 'gs://bucket-encuesta360'