steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/encuesta360-440514/api-encuesta'
      - '.'
images:
  - 'gcr.io/encuesta360-440514/api-encuesta'