steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/encuesta360-440514/mi-imagen'
      - '.'

options:
  logging: CLOUD_STORAGE

build:
  service_account: '503067024564-compute@developer.gserviceaccount.com'
  logs_bucket: 'gs://bucket-encuesta360'